package com.googlecode.lightest.core

/**
 * Provides tabular information to be included in the details generated by a
 * ILightestReporter . A two-column dataset is assumed.*/
interface IReporterInfoSource {

    /**
     * Configures the info source according to the results being reported on.
     *
     * @param result
     */
    void configure(LightestTestResult result)

    /**
     * Returns the type name of this info source. This should be renderable as
     * an XML tag - no whitespace or special characters are allowed.*/
    String getTypeName()

    /**
     * Returns the title of the information.*/
    String getTitle()

    /**
     * Returns a list of headers for the table. This list should have at least
     * two values; any additional values may be ignored.*/
    List<String> getHeaders()

    /**
     * Returns the data as a map of String's to String's.*/
    Map<String, String> getData()
}
